openapi: 3.0.0
info: 
  title: WUMPUS API
  version: 0.0.1
servers:
  - url: http://localhost:8081/
paths:
  /init:
    post:
      summary: Get initial state
      requestBody:
        $ref: '#/components/requestBodies/InitBody'
      responses:
        '5XX':
          description: Rejected or Error
        '2XX':
          description: State Generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Start'
  /debug:
    post:
      summary: Get the default initial state
      responses:
        '5XX':
          description: Rejected or Error
        '2XX':
          description: State Generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Start'
  /forward:
    post:
      summary: Move the character forward
      requestBody:
        $ref: '#/components/requestBodies/ActionBody'
      responses:
        '5XX':
          description: Failure or Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
        '2XX':
          description: Action Completed Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
  /right:
    post:
      summary: Turn the character to the right
      requestBody:
        $ref: '#/components/requestBodies/ActionBody'
      responses:
        '5XX':
          description: Failure or Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
        '2XX':
          description: Action Completed Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
  /left:
    post:
      summary: Turn the character to the left
      requestBody:
        $ref: '#/components/requestBodies/ActionBody'
      responses:
        '5XX':
          description: Failure or Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
        '2XX':
          description: Action Completed Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
  /grab:
    post:
      summary: Attempt to grab the gold
      requestBody:
        $ref: '#/components/requestBodies/ActionBody'
      responses:
        '5XX':
          description: Failure or Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
        '2XX':
          description: Action Completed Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
  /climb:
    post:
      summary: Attempt to climb out of the cave
      requestBody:
        $ref: '#/components/requestBodies/ActionBody'
      responses:
        '5XX':
          description: Failure or Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
        '2XX':
          description: Action Completed Successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActionResult'
components:
  requestBodies:
    InitBody:
      description: Contains the initialization request body
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InitState'
    ActionBody:
      description: Contains the simulation id to be used for an action
      required: true
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/UUID'
  schemas:
    InitState:
      description: Describes the initialization parameters for the simulation
      type: object
      properties:
        height:
          type: integer
        width:
          type: integer
        arrow_num:
          type: integer
        gold_density:
          type: number
        wumpus_density:
          type: number
        pit_density:
          type: number
    Start:
      description: Contains the initial percepts and the user's unique id for his session
      type: object
      properties: 
        percepts:
          type: array
          items:
            type: string
            enum: 
              - breeze
              - stench
              - glitter
        status:
          type: string
        uuid:
          type: string
        
    ActionResult:
      type: object
      properties:
        action:
          type: string
          enum:
            - ok
            - Simulation Halted - You Win
            - Simulation Halted - You Lose (No gold)
            - Simulation Halted - Agent Dead
        percepts:
          type: array
          items:
            type: string
            enum: 
              - breeze
              - stench
              - glitter
              - scream
              - bump
    UUID:
      description: Contains user's unique ID for his current simulation
      type: object
      properties:
        uuid:
          type: string

